#!/usr/bin/env bun
import {
  runMigrations,
  getStats,
  getRecentObservations
} from "./db.js";
import { searchObservations } from "./search.js";
import { existsSync, writeFileSync, appendFileSync, readFileSync, mkdirSync } from "fs";
import { join } from "path";
import { homedir } from "os";

function getDataDir(): string {
  return join(homedir(), ".opencode-memory");
}

const HELP = `opencode-memory CLI

Usage:
  longmem <command> [options]

Commands:
  init                Initialize memory database
  search <query>      Search observations
  pack [options]      Pack context for a CLI
  stats               Show memory statistics
  generate            Generate config files

Pack Options:
  --format=<format>   Output format: opencode, claude, gemini, codex
  --project=<name>    Project name
  --query=<query>     Search query for context

Generate Options:
  --codex             Generate Codex AGENTS files
  --gemini            Generate Gemini CLI config
  --claude            Generate Claude Code wrapper

Examples:
  longmem init
  longmem search "auth bug"
  longmem pack --format=codex --project=myapp
  longmem generate --codex
`;

function parseArgs(args: string[]): { command: string; options: Record<string, string>; positional: string[] } {
  const options: Record<string, string> = {};
  const positional: string[] = [];
  let command = "";
  
  for (const arg of args) {
    if (arg.startsWith("--")) {
      const [key, value] = arg.slice(2).split("=");
      options[key] = value || "true";
    } else if (!command) {
      command = arg;
    } else {
      positional.push(arg);
    }
  }
  
  return { command, options, positional };
}

async function main() {
  const { command, options, positional } = parseArgs(process.argv.slice(2));
  
  if (!command || command === "help" || command === "--help" || command === "-h") {
    console.log(HELP);
    process.exit(0);
  }
  
  switch (command) {
    case "init":
      cmdInit();
      break;
    case "search":
      cmdSearch(positional.join(" "), options);
      break;
    case "pack":
      cmdPack(options);
      break;
    case "stats":
      cmdStats();
      break;
    case "generate":
      cmdGenerate(options);
      break;
    default:
      console.error(`Unknown command: ${command}`);
      console.log(HELP);
      process.exit(1);
  }
}

function cmdInit() {
  console.log("Initializing opencode-memory...");
  runMigrations();
  console.log(`Database created at: ${join(getDataDir(), "memory.db")}`);
  console.log("Done.");
}

function cmdSearch(query: string, options: Record<string, string>) {
  if (!query) {
    console.error("Usage: longmem search <query>");
    process.exit(1);
  }
  
  runMigrations();
  
  const project = options.project;
  const results = searchObservations(query, project);
  
  console.log(`\nFound ${results.length} observations:\n`);
  for (const r of results) {
    const summary = r.compressed_summary || "no summary";
    console.log(`[${r.created_at?.split("T")[0] || "?"}] ${r.tool_name}: ${summary.slice(0, 80)}`);
    if (r.files_referenced) console.log(`  Files: ${r.files_referenced}`);
  }
}

function cmdPack(options: Record<string, string>) {
  const format = options.format || "opencode";
  const project = options.project || process.cwd().split("/").pop() || "default";
  const query = options.query;
  const limit = options.limit ? parseInt(options.limit, 10) : 30;
  
  runMigrations();
  
  const observations = query
    ? searchObservations(query, project, limit)
    : getRecentObservations(project, limit);
  
  if (observations.length === 0) {
    console.log("No context available.");
    return;
  }
  
  const lines: string[] = [];
  
  switch (format) {
    case "codex":
      lines.push("# AGENTS.override.md", "", "> Auto-generated by opencode-memory.", "", "## Recent Context", "");
      for (const obs of observations.slice(0, 12)) {
        const date = obs.created_at?.split("T")[0] || "?";
        lines.push(`### ${date} - ${obs.tool_name}`);
        lines.push(obs.compressed_summary || "No summary");
        if (obs.files_referenced) lines.push(`Files: ${obs.files_referenced}`);
        lines.push("");
      }
      break;
    case "claude":
      lines.push("# Memory Context", "", "Relevant context from previous sessions:", "");
      for (const obs of observations.slice(0, 10)) {
        const date = obs.created_at?.split("T")[0] || "?";
        lines.push(`## ${date} - ${obs.tool_name}`);
        lines.push(obs.compressed_summary || "No summary");
        if (obs.files_referenced) lines.push(`Files: ${obs.files_referenced}`);
        lines.push("");
      }
      break;
    case "gemini":
      lines.push("# Memory Context", "", "Previous session observations:", "");
      for (const obs of observations.slice(0, 10)) {
        lines.push(`- **${obs.tool_name}**: ${obs.compressed_summary || "No summary"}`);
        if (obs.files_referenced) lines.push(`  - Files: ${obs.files_referenced}`);
      }
      break;
    default:
      lines.push("## Previous Session Context", "", "Relevant observations from past sessions:", "");
      for (const obs of observations.slice(0, 10)) {
        const date = obs.created_at?.split("T")[0] || "?";
        lines.push(`- [${date}] **${obs.tool_name}**: ${obs.compressed_summary || "No summary"}`);
        if (obs.files_referenced) lines.push(`  Files: ${obs.files_referenced}`);
      }
  }
  
  console.log(lines.join("\n"));
}

function cmdStats() {
  runMigrations();
  const stats = getStats();
  
  console.log(`
opencode-memory Statistics
==========================
Sessions: ${stats.totalSessions}
Observations: ${stats.totalObservations}
User memories: ${stats.totalUserObservations}
Pending compressions: ${stats.pendingCompressions}
Data directory: ${getDataDir()}
`);
}

function cmdGenerate(options: Record<string, string>) {
  const project = options.project || process.cwd().split("/").pop() || "default";
  const cwd = process.cwd();
  
  if (options.codex) {
    const agentsMd = `# AGENTS.md

Project: ${project}

## Memory Integration

This project uses opencode-memory for persistent context across sessions.

### Quick Commands

- \`longmem stats\` - View memory statistics
- \`longmem search <query>\` - Search observations
- \`longmem pack --format=codex\` - Generate context

### Memory Files

- \`AGENTS.override.md\` - Auto-generated context (gitignored)
- \`~/.opencode-memory/\` - Memory database

### Disable Memory

Create \`.opencode-memory-disable\` in project root.
`;
    
    writeFileSync(join(cwd, "AGENTS.md"), agentsMd);
    
    runMigrations();
    const observations = getRecentObservations(project, 10);
    const overrideLines = [
      "# AGENTS.override.md",
      "",
      "> Auto-generated by opencode-memory. Do not edit.",
      "",
      "## Recent Context",
      ""
    ];
    
    for (const obs of observations) {
      const date = obs.created_at?.split("T")[0] || "?";
      overrideLines.push(`### ${date} - ${obs.tool_name}`);
      overrideLines.push(obs.compressed_summary || "No summary");
      if (obs.files_referenced) overrideLines.push(`Files: ${obs.files_referenced}`);
      overrideLines.push("");
    }
    
    writeFileSync(join(cwd, "AGENTS.override.md"), overrideLines.join("\n"));
    
    const gitignore = join(cwd, ".gitignore");
    if (existsSync(gitignore)) {
      const content = readFileSync(gitignore, "utf-8");
      if (!content.includes("AGENTS.override.md")) {
        appendFileSync(gitignore, "\n# opencode-memory\nAGENTS.override.md\n");
      }
    } else {
      writeFileSync(gitignore, "# opencode-memory\nAGENTS.override.md\n");
    }
    
    console.log("Generated: AGENTS.md, AGENTS.override.md (added to .gitignore)");
  }
  
  if (options.gemini) {
    const geminiDir = join(cwd, ".gemini", "commands");
    if (!existsSync(geminiDir)) {
      mkdirSync(geminiDir, { recursive: true });
    }
    
    const toml = `# .gemini/commands/mem.toml
[commands.mem]
description = "Show memory context"
command = "longmem pack --format=gemini --project=$(basename $PWD)"
`;
    writeFileSync(join(geminiDir, "mem.toml"), toml);
    console.log("Generated: .gemini/commands/mem.toml");
    console.log('\nAdd to ~/.gemini/settings.json:');
    console.log('{ "context": { "fileName": "AGENTS.md" } }');
  }
  
  if (options.claude) {
    const wrapper = `#!/usr/bin/env bash
# claude-mem wrapper - injects memory context into Claude Code

PROJECT=$(basename "$PWD")
CONTEXT=$(longmem pack --format=claude --project="$PROJECT" 2>/dev/null)

if [ -n "$CONTEXT" ]; then
  claude --append-system-prompt "$CONTEXT" "$@"
else
  claude "$@"
fi
`;
    writeFileSync(join(cwd, "claude-mem"), wrapper, { mode: 0o755 });
    console.log("Generated: claude-mem");
    console.log("\nUsage: ./claude-mem \"your prompt here\"");
  }
  
  if (!options.codex && !options.gemini && !options.claude) {
    console.log("Specify what to generate: --codex, --gemini, or --claude");
  }
}

main().catch(console.error);
